### ISSUE TITLE
Won't build in gcc 11.4.0 under Ubuntu 22.04

### ISSUE THREAD

**Issue by xihr** [Lyle-Tafoya/Omega#24]
```
[  1%] Building CXX object CMakeFiles/omega.dir/src/abyss.cpp.o
/home/max/other/Omega/src/abyss.cpp:25:10: fatal error: format: No such file or directory
   25 | #include <format>
      |          ^~~~~~~~
compilation terminated.
```

Just so you know.

**Comment by Lyle-Tafoya** [comment]
Actually, I just tried with Clang 14 and the `-fexperimental-library` compile flag on Ubuntu 22.04, and it seems that flag isn't supported. I'm not sure why. I was basing my information off of https://en.cppreference.com/w/cpp/compiler_support

**Comment by Lyle-Tafoya** [comment]
On Ubuntu 22.04, the following steps can be performed:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install g++-13
git clone https://github.com/Lyle-Tafoya/Omega.git
mkdir Omega/build
cd Omega/build
CXX=g++-13 cmake ..
make
```

**Comment by SilearFlare** [comment]
Can confirm you can actually get it to compile properly if you bother with actually hunting for and installing that specific test GCC 13 repository on ubuntu and ubuntu-adjacent distributions. Thanks for the README addition, it was a bit of an annoying rabbit hole to find it in the first place.

**Comment by Lyle-Tafoya** [comment]
Closing this, since the necessary steps to compile on Ubuntu 22.04 are now in the README

**Comment by xihr** [comment]
Sorry, was out of town for the weekend.  Yep, works after installing g++-13.  Good to go.
